### ISSUE TITLE
Align to changes of Namespace Renaming

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoMAnalytics_Toolkit#3]
#### Broken rules:

Following confirmation [here](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-631687011) the namespace in this toolkit, for all items except the adapter should have the namespace `BH.oM.Adapters.ToolkitName` or `BH.Engine.Adapters.ToolkitName` instead of `BH.oM.ToolkitName`, etc.

The Adapter namespace should remain at `BH.Adapter.ToolkitName` instead of `BH.Adapter.External.ToolkitName`.

➡️ **Also** This should also align with the changes in dependencies: https://github.com/BHoM/Mongo_Toolkit/pull/120

**ALSO make sure that the default namespace is set correctly in the oM and Engine Project properties.**
➡️ [Right click on the project, navigate to the Application tab, and check the default namespace](https://user-images.githubusercontent.com/6352844/90246499-b122da00-de2c-11ea-92c0-edf0fcf81584.png).

#### Suggestions to restore compliance:

As above.

**Comment by adecler** [comment]
@alelom , I will not have time to take care of this for you. 
Can you do this yourself or assigned to someone else, as it is a pretty straightforward task? 
Happy to review when done.

**Comment by alelom** [comment]
> @alelom , I will not have time to take care of this for you.
> Can you do this yourself or assigned to someone else, as it is a pretty straightforward task?
> Happy to review when done.

Hey @adecler, no worries, you can do it next sprint too. I had to resort in postponing the deadline yet again as everyone is always busy. For now, I'm short on time too, and I've done basically 70% of the other renaming myself, as this keeps on falling on me. I'll reassign you as this is connected to https://github.com/BHoM/Mongo_Toolkit/pull/120 which I also prefer if you could make sure is correctly aligned to this.

**Comment by adecler** [comment]
Sure, no problem. I'll get both done beginning of  next milestone.

**Comment by adecler** [comment]
There is currently no change needed on this toolkit regarding the namespace. The reason for it is that the Engine methods and oM classes in that repo are local tools not related to the adapter so it doesn't make sense to have them under the adapter namespace.
